
// Test
pub(crate) mod human {
    pub(crate) mod anshul {
        pub(crate) fn name() {
            println!("My name is {}", "anshul");
            println!("I have a animal friend name: {}", super::super::animal::lion::name())
        }
        //Either you need all struct fields to be public or need impl method
        // which fill hidden fileds and return unfinished object where public
        // fileds can then be updated/inserted by external code.
        // fn lion(name: &str) -> Lion{
        //     Lion{
        //         name: name.parse().unwrap(),
        //         breed: "".to_string()
        //     }
        // }
    }
}



pub mod animal{
    pub(crate) mod lion{
        //I do not know &'static str syntax(yet to find out).
        // this syntax generated by IDE autocorrect
        pub(crate) fn name() -> &'static str {
            println!("{}", "I am Lion the king of jungle");
            return "LION_THE_KING";
        }
    }
    // pub struct Lion {
    //     pub name: String,
    //     breed: String
    // }
}
